### PR TITLE
Download Everest lib-stripped artifact for autobuild

### PR DESCRIPTION
**Pull request by coloursofnoise**
Referenced from the example workflow given in https://github.com/EverestAPI/ExampleMod

### CODE REVIEW

**Comment by swoolcock** [comment]
Going to merge all these and test.

**Comment by swoolcock** [comment]
@coloursofnoise can you please clarify how this works?  From what I can see it looks like it forcefully downloads the latest version of Everest even if that's not the version in the yaml.  I can't see where `EVERESTDEP` is being read.  Also, does the `CELESTEPREFIX` env var get automatically put into `CelestePrefix` in MSBuild?

**Comment by coloursofnoise** [comment]
> I can't see where `EVERESTDEP` is being read

I was referencing one of the [Example Mod workflows](https://github.com/EverestAPI/ExampleMod/blob/master/.github/workflows/autobuild-stable.yml) for this, which is supposed to download the stable version specified in the YAML. However, without adding some sort of clear warning I wasn't confident that users would know to only depend on stable versions, so I removed that part but forgot to remove the setup script.

Making this work reliably *is* possible by using `git describe --contains`, but that would require either cloning the Everest repo as part of the workflow or setting up a separate API for it.

> does the `CELESTEPREFIX` env var get automatically put into `CelestePrefix` in MSBuild?

I didn't test that specific setup, but that's how it's handled in the other workflows I've setup:
https://github.com/EverestAPI/ExampleMod/blob/4e630c993c63b54bb43a82e01f77e74d5af64aeb/.github/workflows/autobuild.yml#L30

**Comment by swoolcock** [comment]
Yeah the changes you made are missing some things, I might roll this back.

**Pull request merged**
