### PR TITLE
Add support for .NET Core installs

### PR DESCRIPTION
**Pull request by Popax21**

### CODE REVIEW

**Comment by swoolcock** [comment]
Where's this at?

**Comment by Popax21** [comment]
> Where's this at?

Should be complete, however as mentioned I have been unable to get a proper test environment working, so this should definitely be checked before being merged.

**Comment by swoolcock** [comment]
I've tested:
* without `--Core` in a non-core Celeste install, successfully compiled 👍 
* with `--Core` in a non-core Celeste install, does not compile, as expected 👍
* without `--Core` in a core Celeste install, does not compile due to not setting up legacyRef (🤷 )
* with `--Core` in a core Celeste install, successfully compiled 👍

**Comment by swoolcock** [comment]
Looks good :glumbsup:

**Pull request merged**
